### ISSUE TITLE
Whether to support the shortest path algorithm

### ISSUE THREAD

**Issue by godlovefei** [wey-gu/nebulagraph-di#36]
An error occurred while running the shortest path algorithm. Does `TBD: ShortestPathAlgo is not yet encodeID compatible` mean that the shortest path algorithm is not supported?
![image](https://user-images.githubusercontent.com/33597028/233925413-7a338b03-4499-444e-a02a-67b1b2ebb9d5.png)

![image](https://user-images.githubusercontent.com/33597028/233925835-fc483654-380f-4c1a-8625-e3360ea7bc13.png)
It's still a problem with the parameters I gave？
Thanks！

**Comment by wey-gu** [comment]
It's not yet supported by upstream (Nebula-Algorithm) with encodeID(string vid to digi-vid mapping) :).

**Comment by wey-gu** [comment]
You could use algo.get_all_algo() to get supported algorithms for now.

Also, you could give networkx engine a try, although shortest path is not imeplemented in ng_ai.algo(), you could get networkx graph and call networkx by yourself.
